# Generated by Django 4.2.7 on 2023-12-06 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("kakao_login", "0002_alter_users_gender_alter_users_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("board_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("body", models.TextField()),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kakao_login.users",
                    ),
                ),
            ],
        ),
    ]
